In [4]:
#HW4:
# Problem_1:NumPy 2-dim Arrays
#1. Creates a 5x6 NumPy array of single-precision floating-point numbers with values ranging from 6.0 
#to 35.0.
#2. Converts the elements of this array to their corresponding square roots.
#3. Adds to the elements of the five rows the values 1., 2., 3., 4., and 5, correspondingly.
#4. Prints the resultant array’s arithmetic mean.

import numpy as np
from numpy.random import rand
#arr=np.random(6,35,size=(5,6),dtype=np.float16)
arr=np.arange(6.0,36.0,dtype=np.float32).reshape(5,6)
arr_sqrt=np.sqrt(arr)
print(arr_sqrt)
x=np.arange(1,6).reshape(5,1)
x.shape
arr.shape
summation=x+arr
print(summation)
np.mean(summation)


[[2.4494898 2.6457512 2.828427  3.        3.1622777 3.3166249]
 [3.4641016 3.6055512 3.7416575 3.8729835 4.        4.1231055]
 [4.2426405 4.358899  4.472136  4.582576  4.690416  4.7958317]
 [4.8989797 5.        5.0990195 5.196152  5.2915025 5.3851647]
 [5.477226  5.5677643 5.656854  5.7445626 5.8309517 5.91608  ]]
[[ 7.  8.  9. 10. 11. 12.]
 [14. 15. 16. 17. 18. 19.]
 [21. 22. 23. 24. 25. 26.]
 [28. 29. 30. 31. 32. 33.]
 [35. 36. 37. 38. 39. 40.]]


23.5

In [ ]:
#HW4:
# Problem_2:Solving a linear system of equations
#Solve the following system of linear equations using NumPy Linear Algebra functions, i.e., find the values of 
#a, b, and c that satisfy the following three equations:
#2𝑎 + 𝑏 + 3𝑐 = 13
#−3𝑎 − 4𝑏 + 7𝑐 = 10
#5𝑎 + 2𝑏 − 𝑐 = 6

In [5]:
from numpy.linalg import solve
a1=np.array([[2,1,3],[-3,-4,7],[5,2,-1]])

b1=np.array([13,10,6])
x=solve(a=a1,b=b1)
print(x)
#check:
np.allclose(np.dot(a1, x), b1)

[1. 2. 3.]


True

In [6]:
#HW4:
#problem_3:Finding the sum of the center of a 3D array
#Consider the following Python code that generates a three-dimensional array. This array has 1,000 
#elements. Imagine that this array is a cube as shown blow.
np.random.seed(7)
a = np.random.randn(10, 10, 10)

np.ndarray.sum(a[1:-1,1:-1,1:-1])


-46.892828225679395

In [7]:
#HW4:
#problem_4: Modifying Arrays
#Problem 04-D: Modifying Arrays
#Consider the following Python code that generates a two-dimensional array of ten rows and 3 columns.
#np.random.seed(7)
#a = np.random.randn(10, 3)
#Write a Python code that replaces every element 𝑖: − 1 < 𝑖 < +1 with the value 0.0, then finds the sum 
#of each column
np.random.seed(7)
a = np.random.randn(10, 3)
a[np.logical_and(a>-1 , a<1)]=0
np.ndarray.sum(a,axis=0)




array([-2.05103081, -3.68253099,  4.69742992])