In [1]:
import numpy as np

x=np.arange(10)
print(x)

data=[[1,2],[3,4]]
arr=np.array(data)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[[1 2]
 [3 4]]


In [3]:
arr.ndim
arr.shape

(2, 2)

In [6]:
a=np.full([2,3,2],7,dtype=np.int32)

In [7]:
a.dtype

dtype('int32')

In [9]:
af=np.array([3.7, -1.2,-2.6,.5])
ai=af.astype(dtype=np.int32)
print(ai)

[ 3 -1 -2  0]


In [12]:
s = np.array(['1.25', 
'-9.6', '42'],
dtype=np.string_)

s.astype(np.float32)

array([ 1.25, -9.6 , 42.  ], dtype=float32)

In [13]:
#equal-size arrays applies the operation element-wise.

arr = np.array([[1., 2., 3.],
                [4., 5., 6.]])
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [14]:
#Operations between differently sized arrays is called broadcasting.

a1 = np.array([[0., 0., 0.],
[1., 1., 1.],
[2., 2., 2.],
[3., 3., 3.]])

a2 = np.array([1., 2., 3.])
a1 + a2


array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.]])

In [24]:
arr = np.arange(6)
arr[3:5]=12
arr

array([ 0,  1,  2, 12, 12,  5])

In [25]:
arr_slice = arr[3:5].copy()
arr_slice[1] = 1000
arr
#important inplace the value to the original numpy array correct by ading .copy()


array([ 0,  1,  2, 12, 12,  5])

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a[0][2]#true
a[1,2]#true

6

In [30]:
a = np.zeros((2, 3, 4))
a[0].shape
#a.shape

(4,)

In [33]:
arr2=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr2[:2,1:]


array([[2, 3],
       [5, 6]])

In [38]:
#The Boolean array must be of the same 
#length as the array axis it’s indexing

names = np.array(['Bob', 'Joe',
'Will', 'Bob', 'Joe'])
#data = np.random.randn(5, 3)
data
data[names=='Bob']
data[names == 'Bob', 2]
data[data < 0] = 0
data

array([[0.        , 0.        , 0.70814769],
       [0.43662827, 0.        , 0.        ],
       [0.11707413, 1.63158595, 0.70156159],
       [0.43951694, 0.        , 0.89666278],
       [0.        , 1.33260914, 0.69956817]])

In [47]:
arr = np.arange(20).reshape((5, 4))
arr
arr[[4,3,0],[0,2,1]]
arr[[1, 2], [0, 2]]

array([ 4, 10])

In [83]:
arr = np.arange(24).reshape((2, 4,3))
arr.T.shape

(3, 4, 2)

In [84]:
arr.transpose((0, 2, 1)).shape

(2, 3, 4)

In [86]:
print(arr.shape)
arr.swapaxes(1, 0).shape

(2, 4, 3)


(4, 2, 3)

In [90]:
a =np.array([[ 1,-1]
            ,[-1, 1]] )
b= np.array([[1, 2]
            ,[3, 4]])

np.where(a < 0,0, a)


array([[1, 0],
       [0, 1]])

In [98]:
arr =np.array( [[1, 2, 3],
[4, 5, 6]])

arr.sum()
arr.cumsum()#cumulative sum
arr.cumprod()#cumulative product


array([  1,   2,   6,  24, 120, 720])

In [102]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
#####Important**********
(arr>4).sum()
(arr>4).any()
(arr>4).all()



False

In [116]:
arr = np.array([[1, 4, 3],
             [5, 2, 6]])
np.sort(arr,axis=None)
np.sort(arr,axis=1)
np.sort(arr,axis=0)
np.sort(arr)

arr



array([[1, 4, 3],
       [5, 2, 6]])

In [121]:
#File Input and Output with Arrays

np.save('array1',arr,)
loaded_arr=np.load('array1.npy')

np.savez('file1.npz',a=arr,b=arr2)
x=np.load('file1.npz')
print(x['a'])
print(x['b'])
a=x['a']
b=x['b']


[[1 4 3]
 [5 2 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [127]:
#linear_algebra:
a*b[:2,:3]
np.dot(a,b) #same as a@b


array([[38, 46, 54],
       [55, 68, 81]])

In [142]:
from  numpy.linalg import inv
from numpy.linalg import det
from numpy.linalg import eigvals

cum_sum_diag_arr=np.diagflat(arr.cumsum())
np.diag(b)
np.trace(cum_sum_diag_arr)
inv(cum_sum_diag_arr)
det(b)
eigvals(b)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [143]:
np.random.randn(2)

array([2.37088616, 0.11068672])

In [155]:
np.random.seed(42)
np.random.normal(loc=3.,
scale=.01, size=(3, 2))

array([[3.00496714, 2.99861736],
       [3.00647689, 3.0152303 ],
       [2.99765847, 2.99765863]])

In [169]:
rng = np.random.RandomState(50)
rng.randn(10)

array([-1.56035211, -0.0309776 , -0.62092842, -1.46458049,  1.41194612,
       -0.47673214, -0.78046921,  1.07026774, -1.2822926 , -1.3274789 ])

In [184]:
from numpy.random import randint,rand,seed,permutation,shuffle,randn,binomial,normal,gamma,uniform
draws=randint(8,size=(4,3))
steps = np.where(draws > 0, 1, -1)
steps


array([[-1,  1, -1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1]])